-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 09:52:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema storeTM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema storeTM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `storeTM` DEFAULT CHARACTER SET utf8 ;
USE `storeTM` ;

-- -----------------------------------------------------
-- Table `storeTM`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeTM`.`stores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeTM`.`directions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeTM`.`directions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ComponentParts` VARCHAR(45) NOT NULL,
  `ReadyProducts` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeTM`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeTM`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `direction_id` INT UNSIGNED NOT NULL,
  `videocards` VARCHAR(45) NOT NULL,
  `processors` VARCHAR(45) NOT NULL,
  `PC` VARCHAR(45) NOT NULL,
  `notebooks` VARCHAR(45) NOT NULL,
  `motherboards` VARCHAR(45) NOT NULL,
  `MobilePhones` VARCHAR(45) NOT NULL,
  `AudioSystems` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_directions1_idx` (`direction_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_directions1`
    FOREIGN KEY (`direction_id`)
    REFERENCES `storeTM`.`directions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeTM`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeTM`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `S/N` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `storeTM`.`categories` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeTM`.`availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeTM`.`availability` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `count` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_availability_stores1_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_availability_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_availability_stores1`
    FOREIGN KEY (`store_id`)
    REFERENCES `storeTM`.`stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_availability_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `storeTM`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeTM`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeTM`.`employee` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_id` INT UNSIGNED NOT NULL,
  `F_Name` VARCHAR(45) NOT NULL,
  `L_Name` VARCHAR(45) NOT NULL,
  `post` VARCHAR(45) NOT NULL,
  `salary` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_stores_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_stores`
    FOREIGN KEY (`store_id`)
    REFERENCES `storeTM`.`stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeTM`.`stores_directions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeTM`.`stores_directions` (
  `store_id` INT UNSIGNED NOT NULL,
  `direction_id` INT UNSIGNED NOT NULL,
  INDEX `fk_stores_has_directions_directions1_idx` (`direction_id` ASC) VISIBLE,
  INDEX `fk_stores_has_directions_stores1_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_stores_has_directions_stores1`
    FOREIGN KEY (`store_id`)
    REFERENCES `storeTM`.`stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stores_has_directions_directions1`
    FOREIGN KEY (`direction_id`)
    REFERENCES `storeTM`.`directions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeTM`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeTM`.`clients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `F_Name` VARCHAR(45) NOT NULL,
  `L_Name` VARCHAR(45) NOT NULL,
  `NumberOfPhone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeTM`.`baskets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeTM`.`baskets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` INT UNSIGNED NOT NULL,
  `employee_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_baskets_clients1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_baskets_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_baskets_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `storeTM`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_baskets_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `storeTM`.`employee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storeTM`.`buying`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storeTM`.`buying` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `basket_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `store_id` INT UNSIGNED NOT NULL,
  `price` FLOAT NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_buying_baskets1_idx` (`basket_id` ASC) VISIBLE,
  INDEX `fk_buying_products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_buying_stores1_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_buying_baskets1`
    FOREIGN KEY (`basket_id`)
    REFERENCES `storeTM`.`baskets` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_buying_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `storeTM`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_buying_stores1`
    FOREIGN KEY (`store_id`)
    REFERENCES `storeTM`.`stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
